import { Injectable } from '@angular/core';
import { Jewells } from 'src/app/shared/models/jewells';
import { tag } from 'src/app/shared/models/tag';

@Injectable({
  providedIn: 'root'
})
export class JewellService {

  constructor() { }

  getAll(): Jewells[] {
    return [
      {
        id: 1,
        price: 220,
        name: "THE PINK MOON- GOLDEN EMBELLISHED EARRINGS",
        favourite: true,
        star: 2.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring1.jpg',
        type: 'Earring',
      },
      {
        id: 2,
        price: 218,
        name: "PAIRED PERIWINKLES- STATEMENT ACRYLIC EARRINGS (DAISY WHITE)",
        favourite: true,
        star: 4.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring2.jpg',
        type: 'Earring',
      },
      {
        id: 3,
        price: 240,
        name: "THE MIRROR IMAGE- GOLDEN GREEN EMBELLISHED EARRINGS ",
        favourite: false,
        star: 4.2,
        material: 'metal',
        imageUrl: '/assets/earrings/earring3.jpg',
        type: 'Earring',
      },
      {
        id: 4,
        price: 320,
        name: "THE ESSENCE OF SPRING - CUTE EMBELLISHED EARRINGS",
        favourite: false,
        star: 3.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring4.jpg',
        type: 'Earring',
      },
      {
        id: 5,
        price: 250,
        name: "THE ROYAL AFFAIR BLUE STUDDED DAZZLING EARRINGS",
        favourite: true,
        star: 2.5,
        material: 'metal',
        imageUrl: '/assets/earrings/earring5.jpg',
        type: 'Earring',
      },
      {
        id: 6,
        price: 349,
        name: "THE ELEGANT STATEMENT MAKERS - BLACK OXIDIXED STUD EARRINGS",
        favourite: true,
        star: 5.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring6.jpg',
        type: 'Earring',
      },
      {
        id: 7,
        price: 210,
        name: "THE FOGGY SKY- GOLDEN PEARL EARRINGS",
        favourite: false,
        star: 4.6,
        material: 'metal',
        imageUrl: '/assets/earrings/earring7.jpg',
        type: 'Earring',
      },
      {
        id: 8,
        price: 220,
        name: "THE AUTUM FEEL - GOLDEN EARRING",
        favourite: false,
        star: 2.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring8.jpg',
        type: 'Earring',
      },
      {
        id: 9,
        price: 290,
        name: "STAR GAZING- GOLDEN BLUE PEARL EARRINGS",
        favourite: false,
        star: 3.0,
        material: 'alloy',
        imageUrl: '/assets/earrings/earring9.jpg',
        type: 'Earring',
      },
      {
        id: 10,
        price: 760,
        name: "THE SUN-KISSED- GOLDEN EMBELLISHED EARRING",
        favourite: false,
        star: 4.0,
        material: 'alloy',
        imageUrl: '/assets/earrings/earring10.jpg',
        type: 'Earring',
      },
      {
        id: 11,
        price: 530,
        name: "THE FOREVER JEWELLS - GOLDEN STATEMENT EARRINGS",
        favourite: true,
        star: 4.0,
        material: 'metal',
        imageUrl: '/assets/earrings/earring11.jpg',
        type: 'Earring',
      },
      {
        id: 12,
        price: 120,
        name: "STUPENDOUS BLOSSOM EARRINGS",
        favourite: false,
        star: 3.4,
        material: 'alloy',
        imageUrl: '/assets/earrings/earring12.jpg',
        type: 'Earring',
      },
      {
        id: 13,
        price: 148,
        name: "WEAR ME KNOT! WHITE PEARL AND BOW DETAILED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace1.jpg',
        type: 'Necklace',
      },
      {
        id: 14,
        price: 220,
        name: "DROPS OF SUNLIGHT- GOLDEN WHITE PEARL CHOKER NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace2.jpg',
        type: 'Necklace',
      },
      {
        id: 15,
        price: 269,
        name: "THE CRYSTAL HAIL- GOLDEN EMBELLISHED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace3.jpg',
        type: 'Necklace',
      },
      {
        id: 16,
        price: 236,
        name: "THE MINI COINS- GOLDEN EMBELLISHED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace4.jpg',
        type: 'Necklace',
      },
      {
        id: 17,
        price: 289,
        name: "THE JADE OYSTERS- GOLDEN GREEN EMBELLISHED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace5.jpg',
        type: 'Necklace',
      },
      {
        id: 18,
        price: 278,
        name: "THE LOST LOVE- GOLDEN EMBELLISHED NECKLACE",
        favourite: true,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace6.jpg',
        type: 'Necklace',
      },
      {
        id: 19,
        price: 165,
        name: "THE NECK LUCK- GOLDEN EMBELLISHED NECKLACE",
        favourite: true,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace7.jpg',
        type: 'Necklace',
      },
      {
        id: 20,
        price: 189,
        name: "THE GOLD STORM- GOLDEN LAYERED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace8.jpg',
        type: 'Necklace',
      },
      {
        id: 21,
        price: 220,
        name: "THE MEMORY RAIN- GOLDEN EMBELLISHED NECKLACE",
        favourite: true,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace9.jpg',
        type: 'Necklace',
      },
      {
        id: 22,
        price: 239,
        name: "THE FLOWER BLESS- SILVER NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace10.jpg',
        type: 'Necklace',
      },
      {
        id: 23,
        price: 220,
        name: "THE MOON REFLECTION- GOLDEN EMBELLISHED LAYERED NECKLACE",
        favourite: false,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace11.jpg',
        type: 'Necklace',
      },
      {
        id: 24,
        price: 220,
        name: "THE TRUE THOUGHTS- GOLDEN EMBELLISHED LAYERED NECKLACE",
        favourite: true,
        star: 2.0,
        material: 'alloy',
        imageUrl: '/assets/necklace/necklace12.jpg',
        type: 'Necklace',
      },
      {
        id: 25,
        price: 256,
        name: "THE FROSTED SUN- GOLDEN PEARL AND RHINESTONE BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet1.jpg',
        type: 'Bracelet',
      },
      {
        id: 26,
        price: 138,
        name: "WEAR THE CHARM - STONE GREEN GOLDEN BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet2.jpg',
        type: 'Bracelet',
      },
      {
        id: 27,
        price: 256,
        name: "THE RAIL OF FLOWERS - SILVER OXIDIZED BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet3.jpg',
        type: 'Bracelet',
      },
      {
        id: 28,
        price: 179,
        name: "BUTTERFLY IN AN OCEN OF PEARLS - STATEMENT SILVER BRACELET",
        favourite: false,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet4.jpg',
        type: 'Bracelet',
      },
      {
        id: 29,
        price: 126,
        name: "FRUITS OF HEAVEN- GOLDEN BEADS BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet5.jpg',
        type: 'Bracelet',
      },
      {
        id: 30,
        price: 256,
        name: "THE OCEAN EFFECT - SILVER BLUE BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet6.jpg',
        type: 'Bracelet',
      },
      {
        id: 31,
        price: 249,
        name: "CHARM IN THE HANDS - SILVER BRACELET",
        favourite: false,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet7.jpg',
        type: 'Bracelet',
      },
      {
        id: 32,
        price: 126,
        name: "BEADS ON THE WRIST - WHITE PEARLS BRACELET",
        favourite: true,
        star: 3.2,
        material: 'alloy',
        imageUrl: '/assets/bracelet/bracelet8.jpg',
        type: 'Bracelet',
      },
      {
        id: 33,
        price: 99,
        name: "HUGS OF AFFECTION - CASUAL SILVER RING",
        favourite: true,
        star: 3.6,
        material: 'alloy',
        imageUrl: '/assets/Ring/ring1.jpg',
        type: 'Finger-Ring',
      },
      {
        id: 34,
        price: 99,
        name: "THE BEAMING BLOOM - OXIDISED BLACK STATEMENT RING",
        favourite: true,
        star: 4.2,
        material: 'alloy',
        imageUrl: '/assets/Ring/ring2.jpg',
        type: 'Finger-Ring',
      },
      {
        id: 35,
        price: 99,
        name: "SONG OF OCEAN - BLUE STONE SILVER RING",
        favourite: true,
        star: 3.8,
        material: 'alloy',
        imageUrl: '/assets/Ring/ring3.jpg',
        type: 'Finger-Ring',
      },
      {
        id: 36,
        price: 99,
        name: "THE SHINY STONE - SILVER RING",
        favourite: false,
        star: 4.3,
        material: 'alloy',
        imageUrl: '/assets/Ring/ring4.jpg',
        type: 'Finger-Ring',
      }

    ]
  }

  getAllJewellsByTag(tag: string): Jewells[] {
    if (tag == 'All')
      return this.getAll()
    else
      return this.getAll().filter(jewell => jewell.type?.includes(tag));
  }

  getAllTag(): tag[] {
    return [
      { name: 'All', count:36 },
      { name: 'Earring', count:12 },
      { name: 'Bracelet', count:8 },
      { name: 'Necklace', count:12 },
      { name: 'Finger-Ring', count:4 }

    ] 
  }

  getJewellById(id:number): Jewells{
    return this.getAll().find(j => j.id == id)!;
  }
}
